### ISSUE TITLE
it's not working probably

### ISSUE THREAD

**Issue by cyb3ralbert** [Valentin-Butorin/rutube_downloader#2]
```
(venv) $ solasence@nj (rutube-download) ~ python do.py
Traceback (most recent call last):
  File "/home/solasence/devel/rutube-download/do.py", line 3, in <module>
    rt = Rutube('https://rutube.ru/video/somehash/')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/solasence/devel/rutube-download/venv/lib/python3.12/site-packages/rutube.py", line 42, in __init__
    self._m3u8_url = self._get_m3u8_url()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/solasence/devel/rutube-download/venv/lib/python3.12/site-packages/rutube.py", line 95, in _get_m3u8_url
    return self._data['video_balancer']['m3u8']
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'video_balancer'
```

**Comment by cyb3ralbert** [comment]
Probably it is about typo. I will close. thank you!
